name: Clang Analyzer

on:
  pull_request:
    branches: [ master ]

jobs:
  clang:
    name: Clang Analyzer
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: Install dependencies and clang-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev gettext clang-tools
    - name: Analyze
      run: scan-build --status-bugs -v make -j 2
      env:
        FHEROES2_STRICT_COMPILATION: ON
        WITH_TOOLS: ON
