name: Clang Analyzer

on:
  pull_request:
    branches: [ master ]

jobs:
  clang:
    name: Clang Analyzer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: Install dependencies and clang-tools
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev gettext clang-tools-10
    - name: Setup clang-tools
      run: |
        sudo update-alternatives --install /usr/bin/scan-build scan-build /usr/bin/scan-build-10 100
    - name: Analyze
      run: scan-build --status-bugs -v make -j 2
      env:
        FHEROES2_STRICT_COMPILATION: ON
        WITH_TOOLS: ON
