name: Linux

on:
  pull_request:
    branches: [ master ]

jobs:
  sdl1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 1
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libsdl-image1.2-dev gettext
    - name: compile
      run: make -j 2
      env:
        FHEROES2_SDL1: "ON"
        FHEROES2_STRICT_COMPILATION: "ON"
  sdl2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 2
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev gettext
    - name: compile
      run: make -j 2
      env:
        FHEROES2_STRICT_COMPILATION: "ON"
