name: macOS

on:
  pull_request:
    branches: [ master ]

jobs:
  sdl1:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 1
      run: |
        brew install sdl sdl_ttf sdl_mixer sdl_image
    - name: compile
      run: make -j 2
      env:
        FHEROES2_SDL1: "ON"
        FHEROES2_STRICT_COMPILATION: "ON"
        HOMEBREW_NO_AUTO_UPDATE: 1
  sdl2:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 2
      run: |
        brew install sdl2 sdl2_ttf sdl2_mixer sdl2_image
    - name: compile
      run: make -j 2
      env:
        FHEROES2_STRICT_COMPILATION: "ON"
        HOMEBREW_NO_AUTO_UPDATE: 1
