name: macOS (release)

on:
  push:
    branches: [ master ]

jobs:
  sdl1:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - uses: Homebrew/actions/setup-homebrew@master
    - name: install SDL 1
      run: |
        brew install sdl sdl_ttf sdl_mixer sdl_image
    - name: compile
      run: make -j 2
      env:
        FHEROES2_SDL1: "ON"
        FHEROES2_STRICT_COMPILATION: "ON"
        HOMEBREW_NO_AUTO_UPDATE: 1
    - name: create package
      run: |
        cp doc/README.txt script/demo/demo_unix.sh .
        zip fheroes2_macos10_15_sdl1.zip fheroes2 LICENSE fheroes2.key script/macos/install_sdl_1.sh demo_unix.sh changelog.txt README.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: fheroes2_macos10_15_sdl1.zip
        body: ${{ github.event.commits[0].message }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: MacOS build with SDL 1 support (latest commit)
        tag: fheroes2-osx-sdl1_dev
        allowUpdates: true
        prerelease: true
        replacesArtifacts: true
  sdl2:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - uses: Homebrew/actions/setup-homebrew@master
    - name: install SDL 2
      run: |
        brew install sdl2 sdl2_ttf sdl2_mixer sdl2_image
    - name: compile
      run: make -j 2
      env:
        FHEROES2_STRICT_COMPILATION: "ON"
        HOMEBREW_NO_AUTO_UPDATE: 1
    - name: create package
      run: |
        cp doc/README.txt script/demo/demo_unix.sh .
        zip fheroes2_macos10_15_sdl2.zip fheroes2 LICENSE fheroes2.key script/macos/install_sdl_2.sh demo_unix.sh changelog.txt README.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: fheroes2_macos10_15_sdl2.zip
        body: ${{ github.event.commits[0].message }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: MacOS build with SDL 2 support (latest commit)
        tag: fheroes2-osx-sdl2_dev
        allowUpdates: true
        prerelease: true
        replacesArtifacts: true
