name: OSX (release)

on:
  push:
    branches: [ master ]

jobs:
  sdl1:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 1
      run: |
        brew update
        brew install sdl
        brew install sdl_ttf
        brew install sdl_mixer
        brew install sdl_image
    - name: compile
      run: make -j 2
    - name: create package
      run: |
        cp doc/README.txt .
        zip fheroes2_osx_sdl1.zip fheroes2 LICENSE fheroes2.key script/macos/install_sdl_1.sh script/demo/demo_macos.sh changelog.txt README.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: fheroes2_osx_sdl1.zip
        body: Compiled version of ${{ github.sha }} commit
        token: ${{ secrets.GITHUB_TOKEN }}
        name: MacOS build with SDL 1 support (latest commit)
        tag: fheroes2-osx-sdl1_dev
        allowUpdates: true
        prerelease: true
        replacesArtifacts: true
  sdl2:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 2
      run: |
        brew update
        brew install sdl2
        brew install sdl2_ttf
        brew install sdl2_mixer
        brew install sdl2_image
    - name: compile
      run: make -j 2
      env:
        WITH_SDL2: "ON"
        FHEROES2_STRICT_COMPILATION: "ON"
    - name: create package
      run: |
        cp doc/README.txt .
        zip fheroes2_osx_sdl2.zip fheroes2 LICENSE fheroes2.key script/macos/install_sdl_2.sh script/demo/demo_macos.sh  changelog.txt README.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: fheroes2_osx_sdl2.zip
        body: Compiled version of ${{ github.sha }} commit
        token: ${{ secrets.GITHUB_TOKEN }}
        name: MacOS build with SDL 2 support (latest commit)
        tag: fheroes2-osx-sdl2_dev
        allowUpdates: true
        prerelease: true
        replacesArtifacts: true
